# Generated by Django 5.2 on 2025-05-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_negocio_id_alter_negocio_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='horario_apertura',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='horario_cierre',
        ),
        migrations.AlterField(
            model_name='negocio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
